### ISSUE TITLE
Unhandled exception when use loader.exe on 3.22.0 data

### ISSUE THREAD

**Issue by alistair3149** [StarCitizenWiki/scunpacked#5]
Got the following error when attempting to run the loader through 3.22.0 data.

```
Unhandled exception. System.InvalidOperationException: scdb.Xml.Entities.EntityClassDefinition cannot be serialized because it does not have a parameterless constructor.
   at System.Xml.Serialization.TypeDesc.CheckSupported()
   at System.Xml.Serialization.TypeScope.GetTypeDesc(Type, MemberInfo, Boolean, Boolean)
   at System.Xml.Serialization.TypeScope.GetTypeDesc(Type, MemberInfo, Boolean)
   at System.Xml.Serialization.ModelScope.GetTypeModel(Type, Boolean)
   at System.Xml.Serialization.ModelScope.GetTypeModel(Type)
   at System.Xml.Serialization.XmlReflectionImporter.ImportTypeMapping(Type, XmlRootAttribute , String )
   at System.Xml.Serialization.XmlSerializer.GenerateXmlTypeMapping(Type type, XmlAttributeOverrides overrides, Type[] extraTypes, XmlRootAttribute root, String defaultNamespace)
   at System.Xml.Serialization.XmlSerializer..ctor(Type type, XmlAttributeOverrides overrides, Type[] extraTypes, XmlRootAttribute root, String defaultNamespace, String location)
   at System.Xml.Serialization.XmlSerializer..ctor(Type type, XmlRootAttribute root)
   at Loader.ClassParser`1.Parse(String)
   at Loader.EntityService.LoadEntity(String)
   at Loader.EntityService.BuildItemDirectory(String)
   at Loader.EntityService.Initialise(Boolean)
   at Loader.Program.Main(String[])
   ```

**Comment by octfx** [comment]
Hmm thats weird, did the console show the file it was trying to process?

**Comment by alistair3149** [comment]
No sadly, that's the only message I got

**Comment by alistair3149** [comment]
Okay found the file, it is:
`Data\Libs\Foundry\Records\entities\scitem\aimodule_atc_grimhex.xml`
