### ISSUE TITLE
Unhandled exception when extract 3.23.1 LIVE data

### ISSUE THREAD

**Issue by alistair3149** [StarCitizenWiki/scunpacked#6]
```
EntityService: Can't find the filename of the EntityClassDefinition for ARGO_MPUV_Door_Int_Rear
EntityService: Can't find the filename of the EntityClassDefinition for Door_Ship_Exterior_ARGO_Cargo_Left_MS
EntityService: Can't find the filename of the EntityClassDefinition for Door_Ship_Exterior_ARGO_Cargo_Right_MS
EntityService: Can't find the filename of the EntityClassDefinition for ARGO_MPUV_SCItem_SeatAccess_Maelstrom_Pod
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Loader.ItemBuilder.BuildTagList(EntityClassDefinition entity)
   at Loader.ItemBuilder.BuildItem(EntityClassDefinition entity)
   at Loader.ItemInstaller.InstallLoadout(StandardisedItemPort port, List`1 loadout)
   at Loader.ItemInstaller.InstallLoadout(List`1 ports, List`1 loadout)
   at Loader.ItemInstaller.InstallLoadout(StandardisedItem item, List`1 loadout)
   at Loader.ItemLoader.Load(String typeFilter)
   at Loader.Program.Main(String[] args)
```

**Comment by octfx** [comment]
Did you use the latest release?  
This should be fixed in https://github.com/StarCitizenWiki/scunpacked/releases/tag/704c96a4

**Comment by octfx** [comment]
Fixed in https://github.com/StarCitizenWiki/scunpacked/releases/tag/7305a164
